<a href="https://colab.research.google.com/github/karginb/classifications_with_tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[7,8],[10,8]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  8],
       [10,  8]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[10.,7.],
                             [3.,2.],
                             [8.,9.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [2,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (n can be any number)

### Creating tensors with tf.Variable

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10.7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.7], dtype=float32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0] = 7

TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

# Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers


In [ ]:
random1 = tf.random.Generator.from_seed(32)
random1 = random1.normal(shape = (3,2))
random2 = tf.random.Generator.from_seed(32)
random2 = random2.normal(shape = (3,2))
random1,random2, random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182,  1.585549 ],
        [ 0.4356279,  0.2364518],
        [-0.1589871,  1.302304 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182,  1.585549 ],
        [ 0.4356279,  0.2364518],
        [-0.1589871,  1.302304 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:

tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

# Other ways to make tensors
Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.

In [ ]:
tf.ones(shape  = (3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
A = tf.constant(numpy_A,shape = [2,4,3])
numpy_A,A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

# Getting information from tensors(shape,rank,size)
There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:

* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
*  Size: The total number of items in the tensor.

You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

In [ ]:
rank_4_tensor = tf.zeros(shape = [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element:",rank_4_tensor.dtype)
print("Number of dimensions:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along axis 0 of tensor:",rank_4_tensor.shape[0])
print("Elements along last axis of tensor:",rank_4_tensor.shape[-1])
print("Total number of elements:",tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements: 120


In [ ]:
# Get the first 2 items of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7],[3,4]])

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_2_tensor,rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]], dtype=int32)>)

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating tensors(tensor operations)
**Basic Operations**

+,-,*,/

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

One of the most common operations in machine learning algorithms is matrix multiplication.
TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

1.The inner dimensions must match:
* (3, 5) @ (3, 5) won't work
* (5, 3) @ (3, 5) will work
* (3, 5) @ (5, 3) will work
2.The resulting matrix has the shape of the outer dimensions:
* (5, 3) @ (3, 5) -> (5, 5)
* (3, 5) @ (5, 3) -> (3, 3)

🔑 Note: '@' in Python is the symbol for matrix multiplication.



In [ ]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])


Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
X @ Y

InvalidArgumentError: ignored

Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

* Reshape X to (2, 3) so it's (2, 3) @ (3, 2).
* Reshape Y to (3, 2) so it's (3, 2) @ (2, 3).

We can do this with either:

* tf.reshape() - allows us to reshape a tensor into a defined shape.
* tf.transpose() - switches the dimensions of a given tensor.

In [ ]:
tf.reshape(Y,shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
X @ tf.reshape(Y,shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(a = X, b = Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### The dot product

Multiplying matrices by eachother is also referred to as the dot product.

You can perform the tf.matmul() operation using tf.tensordot().


In [ ]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

They result in different values.

Which is strange because when dealing with Y (a (3x2) matrix), reshaping to (2, 3) and tranposing it result in the same shape.

In [ ]:
Y.shape, tf.reshape(Y,(2,3)).shape, tf.transpose(Y).shape
#But calling tf.reshape() and tf.transpose() on Y don't necessarily result in the same values.

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [ ]:
# Checking values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


As you can see, the outputs of tf.reshape() and tf.transpose() when called on Y, even though they have the same shape, are different.

This can be explained by the default behaviour of each method:

* tf.reshape() - change the shape of the given tensor (first) and then insert values in order they appear (in our case, 7, 8, 9, 10, 11, 12).

* tf.transpose() - swap the order of the axes, by default the last axis becomes the first, however the order can be changed using the perm parameter.

# Changing the datatype of a tensor

In [ ]:
B = tf.constant([1.7,7.4])

C = tf.constant([1,7])
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [ ]:
B = tf.cast(B, dtype = tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
C = tf.cast(C, dtype = tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

## Gettting absolute value
Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use tf.abs().

In [ ]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Finding the min, max, mean, sum (aggregation)
You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

* tf.reduce_min() - find the minimum value in a tensor.
* tf.reduce_max() - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* tf.reduce_mean() - find the mean of all elements in a tensor.
* tf.reduce_sum() - find the sum of all elements in a tensor.

Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().

In [ ]:
E = tf.constant(np.random.randint(0,100,size = 50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([20, 70, 31, 79, 93, 53, 49, 57, 11, 80, 29, 15, 60, 30, 52, 84, 79,
       87, 49, 78,  9, 92, 27,  5, 19,  9, 63, 64, 67, 85, 32, 34, 16, 42,
       21, 57, 13, 60, 83, 65, 11, 80, 93, 22, 98, 72, 82, 90, 78, 32])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2627>

You can also find the standard deviation (tf.reduce_std()) and variance (tf.reduce_variance()) of elements in a tensor using similar methods.


## Finding the positional maximum and minimum
How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say ['Green', 'Blue', 'Red']) with your prediction probabilities tensor (e.g. [0.98, 0.01, 0.01]).

In this case, the predicted label (the one with the highest prediction probability) would be 'Green'.

You can do the same for the minimum (if required) with the following:

* tf.argmax() - find the position of the maximum element in a given tensor.
* tf.argmin() - find the position of the minimum element in a given tensor.

In [ ]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.77040047, 0.95215594, 0.64812512, 0.64562614, 0.56948885,
       0.50920649, 0.41400421, 0.98842578, 0.66842092, 0.87476857,
       0.98038513, 0.391308  , 0.49377203, 0.80177906, 0.97971693,
       0.2954916 , 0.8404678 , 0.99973442, 0.15396697, 0.03039475,
       0.84099689, 0.79026245, 0.52453027, 0.10149622, 0.33500481,
       0.08229846, 0.71952143, 0.14661824, 0.27285978, 0.1233006 ,
       0.32330735, 0.31195211, 0.41507646, 0.52352782, 0.86006806,
       0.56821289, 0.48859603, 0.48067702, 0.90395877, 0.59766406,
       0.07173646, 0.04603539, 0.66273209, 0.00874251, 0.93478176,
       0.07931673, 0.5656822 , 0.62182769, 0.92353831, 0.55373226])>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [ ]:
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}")
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}")
print(f"The minimum value of F is at position: {tf.argmin(F).numpy()}")
print(f"The minimum value of F is: {tf.reduce_min(F).numpy()}")
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Using tf.argmin() to index F, the minimum value of F is: {F[tf.argmin(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 17
The maximum value of F is: 0.9997344175072633
The minimum value of F is at position: 43
The minimum value of F is: 0.008742512573464034
Using tf.argmax() to index F, the maximum value of F is: 0.9997344175072633
Using tf.argmin() to index F, the minimum value of F is: 0.008742512573464034
Are the two max values the same (they should be)? True


## Squeezing a tensor (removing all single dimensions)
If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

* tf.squeeze() - remove all dimensions of 1 from a tensor.

In [ ]:
G = tf.constant(np.random.randint(0,100,50), shape = (1,1,1,1,50))
G.shape,G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape,G_squeezed.ndim

(TensorShape([50]), 1)

## One-hot encoding
If you have a tensor of indicies and would like to one-hot encode it, you can use tf.one_hot().

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [ ]:
some_list = [0,1,3,4]

tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, on_value ="we're here", off_value = "we're not here", depth = 4)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"we're here", b"we're not here", b"we're not here",
        b"we're not here"],
       [b"we're not here", b"we're here", b"we're not here",
        b"we're not here"],
       [b"we're not here", b"we're not here", b"we're not here",
        b"we're here"],
       [b"we're not here", b"we're not here", b"we're not here",
        b"we're not here"]], dtype=object)>

## Squaring, log, square root
Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

* tf.square() - get the square of every value in a tensor.
* tf.sqrt() - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).
* tf.math.log() - get the natural log of every value in a tensor (elements need to floats).

In [ ]:
H = tf.constant(np.arange(1,10))
H

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
tf.sqrt(H)

InvalidArgumentError: ignored

In [ ]:
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>


## Manipulating tf.Variable tensors
Tensors created with tf.Variable() can be changed in place using methods such as:

* .assign() - assign a different value to a particular index of a variable tensor.
* .assign_add() - add to an existing value and reassign it at a particular index of a variable tensor.

In [ ]:
I = tf.Variable(np.arange(0, 5))
I


<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
I.assign_add([10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

## Tensors and NumPy
We've seen some examples of tensors interact with NumPy arrays, such as, using NumPy arrays to create tensors.

Tensors can also be converted to NumPy arrays using:

* np.array() - pass a tensor to convert to an ndarray (NumPy's main datatype).
* tensor.numpy() - call on a tensor to convert to an ndarray.

Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [ ]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# By default tensors have dtype=float32, where as NumPy arrays have dtype=float64.
#This is because neural networks (which are usually built with TensorFlow) can generally work very well with less precision (32-bit rather than 64-bit).
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)